### ISSUE TITLE
Discuss whether to use username or not

### ISSUE THREAD

**Issue by smanilov** [Semerkosa/3vial#14]

**Comment by smanilov** [comment]
@ANeshkova @stspot

**Comment by Semerkosa** [comment]
Предполагам, че можем да минем и без username като адресираме даден потребител по име и/или фамилия. "Welcome, George", например.

**Comment by ANeshkova** [comment]
И аз мисля, че не ни е необходим username, а first name, last name и email са напълно достатъчни.

**Comment by smanilov** [comment]
Decided not to use usernames ATM. See #16 as potential follow-up.
