### ISSUE TITLE
Basic connection to eToro API

### ISSUE THREAD

**Issue by smanilov** [Semerkosa/3vial#15]
Create some script / simple app that connects to the API and pulls some data.

Figure out the output format.

**Comment by smanilov** [comment]
Please outline problems in a doc and share with the team.

**Comment by bnenov** [comment]
Adding file which describes the current findings for eToro APIs 

[eToro API Info.docx](https://github.com/Semerkosa/3vial/files/7236282/eToro.API.Info.docx)

**Comment by smanilov** [comment]
Closing, to avoid waiting for token.
