### ISSUE TITLE
Create initial Development Guidelines document

### ISSUE THREAD

**Issue by bnenov** [Semerkosa/3vial#38]
A document which servers as guidelines for creating and developing the projects. The purpose is to standardize the development process.

**Comment by bnenov** [comment]
Initial guidelines document.
[Project Development Guidelines v0.1.docx](https://github.com/Semerkosa/3vial/files/7257368/Project.Development.Guidelines.v0.1.docx)

**Comment by bnenov** [comment]
@Semerkosa @stspot @ANeshkova @GGerginov @smanilov @plm012 Моля прегледайте документа, когато имате възможност.

**Comment by Semerkosa** [comment]
@bnenov Създай PR, за да одобрим

**Comment by bnenov** [comment]
> @bnenov Създай PR, за да одобрим

@Semerkosa, не се ли разбрахме, че когато няма код няма да правим PR?

**Comment by Semerkosa** [comment]
Правилно...Аз и по-рано като създавах asset се водих по документа, така че одобрявам 😅
