### ISSUE TITLE
Define the database schema

### ISSUE THREAD

**Issue by smanilov** [Semerkosa/3vial#4]
Create an entity relationship (ER) diagram, following the specification doc.

Transaction table must include these datapoints:
- Source 
- Timestamp
 - Quantity
-  Price 
- FX rate
- Unrealized gain/loss
- Realized gain/loss
- Interest/Dividents

Consider using: www.lucidchart.com

**Comment by GGerginov** [comment]
[Blank diagram.pdf](https://github.com/Semerkosa/3vial/files/7205139/Blank.diagram.pdf)

Според мен така трябва да изглежда базата. Отворен съм за още идеи.

**Comment by smanilov** [comment]
Моля, хвърлете по едно око, @Semerkosa , @ANeshkova , @stspot , @plm012

**Comment by ANeshkova** [comment]
Предлагам в User вместо username да е email, за да може потребителят да влиза и чрез други платформи (google, facebook и т.н.). И за потребителя ще е по-лесно, защото email-ът му със сигурност ще е уникален и ще избегне досадното измисляне на username (под досадно имам предвид - потребителското име: "вече е заето", "трябва да съдържа поне една главна буква; малка буква; число; специален символ и т.н.").

**Comment by Semerkosa** [comment]
1) Съгласен съм, че трябва да пазим имейла с цел потребителят да се регистрира и логва с него. 

2) Трябва ли ни всъщност username? Веднъж влязъл в своя акаунт, как ще адресираме съответния потребител и какво искаме да вижда той, когато преглежда своя профил? Неговите първо и последно име или неговия username?

**Comment by smanilov** [comment]
2. го обсъдихме в #14
